version: "3.7"

services:
    backend:
        image: petercha2000/dueldice:backend
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/amd64
        restart: always
        networks:
            gate_net:
                aliases:
                    - dueldice
networks:
    gate_net:
        driver: bridge
        external: true
